In [21]:
import pandas as pd
letters =['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
df = pd.DataFrame({'h1':letters})
df1=df.cumsum(axis=0)
df1

                            h1
0                            A
1                           AB
2                          ABC
3                         ABCD
4                        ABCDE
5                       ABCDEF
6                      ABCDEFG
7                     ABCDEFGH
8                    ABCDEFGHI
9                   ABCDEFGHIJ
10                 ABCDEFGHIJK
11                ABCDEFGHIJKL
12               ABCDEFGHIJKLM
13              ABCDEFGHIJKLMN
14             ABCDEFGHIJKLMNO
15            ABCDEFGHIJKLMNOP
16           ABCDEFGHIJKLMNOPQ
17          ABCDEFGHIJKLMNOPQR
18         ABCDEFGHIJKLMNOPQRS
19        ABCDEFGHIJKLMNOPQRST
20       ABCDEFGHIJKLMNOPQRSTU
21      ABCDEFGHIJKLMNOPQRSTUV
22     ABCDEFGHIJKLMNOPQRSTUVW
23    ABCDEFGHIJKLMNOPQRSTUVWX
24   ABCDEFGHIJKLMNOPQRSTUVWXY
25  ABCDEFGHIJKLMNOPQRSTUVWXYZ

In [55]:
m=df1.h1.tolist()
m.reverse()
m

['ABCDEFGHIJKLMNOPQRSTUVWXYZ',
 'ABCDEFGHIJKLMNOPQRSTUVWXY',
 'ABCDEFGHIJKLMNOPQRSTUVWX',
 'ABCDEFGHIJKLMNOPQRSTUVW',
 'ABCDEFGHIJKLMNOPQRSTUV',
 'ABCDEFGHIJKLMNOPQRSTU',
 'ABCDEFGHIJKLMNOPQRST',
 'ABCDEFGHIJKLMNOPQRS',
 'ABCDEFGHIJKLMNOPQR',
 'ABCDEFGHIJKLMNOPQ',
 'ABCDEFGHIJKLMNOP',
 'ABCDEFGHIJKLMNO',
 'ABCDEFGHIJKLMN',
 'ABCDEFGHIJKLM',
 'ABCDEFGHIJKL',
 'ABCDEFGHIJK',
 'ABCDEFGHIJ',
 'ABCDEFGHI',
 'ABCDEFGH',
 'ABCDEFG',
 'ABCDEF',
 'ABCDE',
 'ABCD',
 'ABC',
 'AB',
 'A']

In [56]:
df1.insert(0,'h2',m)

In [57]:
df1

                            h2                          h1
0   ABCDEFGHIJKLMNOPQRSTUVWXYZ                           A
1    ABCDEFGHIJKLMNOPQRSTUVWXY                          AB
2     ABCDEFGHIJKLMNOPQRSTUVWX                         ABC
3      ABCDEFGHIJKLMNOPQRSTUVW                        ABCD
4       ABCDEFGHIJKLMNOPQRSTUV                       ABCDE
5        ABCDEFGHIJKLMNOPQRSTU                      ABCDEF
6         ABCDEFGHIJKLMNOPQRST                     ABCDEFG
7          ABCDEFGHIJKLMNOPQRS                    ABCDEFGH
8           ABCDEFGHIJKLMNOPQR                   ABCDEFGHI
9            ABCDEFGHIJKLMNOPQ                  ABCDEFGHIJ
10            ABCDEFGHIJKLMNOP                 ABCDEFGHIJK
11             ABCDEFGHIJKLMNO                ABCDEFGHIJKL
12              ABCDEFGHIJKLMN               ABCDEFGHIJKLM
13               ABCDEFGHIJKLM              ABCDEFGHIJKLMN
14                ABCDEFGHIJKL             ABCDEFGHIJKLMNO
15                 ABCDEFGHIJK            ABCDEFGHIJKLMNOP
16                  ABCDEFGHIJ           ABCDEFGHIJKLMNOPQ
17                   ABCDEFGHI          ABCDEFGHIJKLMNOPQR
18                    ABCDEFGH         ABCDEFGHIJKLMNOPQRS
19                     ABCDEFG        ABCDEFGHIJKLMNOPQRST
20                      ABCDEF       ABCDEFGHIJKLMNOPQRSTU
21                       ABCDE      ABCDEFGHIJKLMNOPQRSTUV
22                        ABCD     ABCDEFGHIJKLMNOPQRSTUVW
23                         ABC    ABCDEFGHIJKLMNOPQRSTUVWX
24                          AB   ABCDEFGHIJKLMNOPQRSTUVWXY
25                           A  ABCDEFGHIJKLMNOPQRSTUVWXYZ

In [59]:
df1.insert(2,'h3',df1.h1.tolist())
df1

,h2,h1,h3
0,ABCDEFGHIJKLMNOPQRSTUVWXYZ,A,A
1,ABCDEFGHIJKLMNOPQRSTUVWXY,AB,AB
2,ABCDEFGHIJKLMNOPQRSTUVWX,ABC,ABC
3,ABCDEFGHIJKLMNOPQRSTUVW,ABCD,ABCD
4,ABCDEFGHIJKLMNOPQRSTUV,ABCDE,ABCDE
5,ABCDEFGHIJKLMNOPQRSTU,ABCDEF,ABCDEF
6,ABCDEFGHIJKLMNOPQRST,ABCDEFG,ABCDEFG
7,ABCDEFGHIJKLMNOPQRS,ABCDEFGH,ABCDEFGH
8,ABCDEFGHIJKLMNOPQR,ABCDEFGHI,ABCDEFGHI
9,ABCDEFGHIJKLMNOPQ,ABCDEFGHIJ,ABCDEFGHIJ
10,ABCDEFGHIJKLMNOP,ABCDEFGHIJK,ABCDEFGHIJK
11,ABCDEFGHIJKLMNO,ABCDEFGHIJKL,ABCDEFGHIJKL
12,ABCDEFGHIJKLMN,ABCDEFGHIJKLM,ABCDEFGHIJKLM
13,ABCDEFGHIJKLM,ABCDEFGHIJKLMN,ABCDEFGHIJKLMN
14,ABCDEFGHIJKL,ABCDEFGHIJKLMNO,ABCDEFGHIJKLMNO
15,ABCDEFGHIJK,ABCDEFGHIJKLMNOP,ABCDEFGHIJKLMNOP
16,ABCDEFGHIJ,ABCDEFGHIJKLMNOPQ,ABCDEFGHIJKLMNOPQ
17,ABCDEFGHI,ABCDEFGHIJKLMNOPQR,ABCDEFGHIJKLMNOPQR
18,ABCDEFGH,ABCDEFGHIJKLMNOPQRS,ABCDEFGHIJKLMNOPQRS
19,ABCDEFG,ABCDEFGHIJKLMNOPQRST,ABCDEFGHIJKLMNOPQRST
20,ABCDEF,ABCDEFGHIJKLMNOPQRSTU,ABCDEFGHIJKLMNOPQRSTU
21,ABCDE,ABCDEFGHIJKLMNOPQRSTUV,ABCDEFGHIJKLMNOPQRSTUV
22,ABCD,ABCDEFGHIJKLMNOPQRSTUVW,ABCDEFGHIJKLMNOPQRSTUVW
23,ABC,ABCDEFGHIJKLMNOPQRSTUVWX,ABCDEFGHIJKLMNOPQRSTUVWX
24,AB,ABCDEFGHIJKLMNOPQRSTUVWXY,ABCDEFGHIJKLMNOPQRSTUVWXY
25,A,ABCDEFGHIJKLMNOPQRSTUVWXYZ,ABCDEFGHIJKLMNOPQRSTUVWXYZ

In [63]:
df1

,h2,h1,h3
0,ABCDEFGHIJKLMNOPQRSTUVWXYZ,A,A
1,ABCDEFGHIJKLMNOPQRSTUVWXY,AB,AB
2,ABCDEFGHIJKLMNOPQRSTUVWX,ABC,ABC
3,ABCDEFGHIJKLMNOPQRSTUVW,ABCD,ABCD
4,ABCDEFGHIJKLMNOPQRSTUV,ABCDE,ABCDE
5,ABCDEFGHIJKLMNOPQRSTU,ABCDEF,ABCDEF
6,ABCDEFGHIJKLMNOPQRST,ABCDEFG,ABCDEFG
7,ABCDEFGHIJKLMNOPQRS,ABCDEFGH,ABCDEFGH
8,ABCDEFGHIJKLMNOPQR,ABCDEFGHI,ABCDEFGHI
9,ABCDEFGHIJKLMNOPQ,ABCDEFGHIJ,ABCDEFGHIJ
10,ABCDEFGHIJKLMNOP,ABCDEFGHIJK,ABCDEFGHIJK
11,ABCDEFGHIJKLMNO,ABCDEFGHIJKL,ABCDEFGHIJKL
12,ABCDEFGHIJKLMN,ABCDEFGHIJKLM,ABCDEFGHIJKLM
13,ABCDEFGHIJKLM,ABCDEFGHIJKLMN,ABCDEFGHIJKLMN
14,ABCDEFGHIJKL,ABCDEFGHIJKLMNO,ABCDEFGHIJKLMNO
15,ABCDEFGHIJK,ABCDEFGHIJKLMNOP,ABCDEFGHIJKLMNOP
16,ABCDEFGHIJ,ABCDEFGHIJKLMNOPQ,ABCDEFGHIJKLMNOPQ
17,ABCDEFGHI,ABCDEFGHIJKLMNOPQR,ABCDEFGHIJKLMNOPQR
18,ABCDEFGH,ABCDEFGHIJKLMNOPQRS,ABCDEFGHIJKLMNOPQRS
19,ABCDEFG,ABCDEFGHIJKLMNOPQRST,ABCDEFGHIJKLMNOPQRST
20,ABCDEF,ABCDEFGHIJKLMNOPQRSTU,ABCDEFGHIJKLMNOPQRSTU
21,ABCDE,ABCDEFGHIJKLMNOPQRSTUV,ABCDEFGHIJKLMNOPQRSTUV
22,ABCD,ABCDEFGHIJKLMNOPQRSTUVW,ABCDEFGHIJKLMNOPQRSTUVW
23,ABC,ABCDEFGHIJKLMNOPQRSTUVWX,ABCDEFGHIJKLMNOPQRSTUVWX
24,AB,ABCDEFGHIJKLMNOPQRSTUVWXY,ABCDEFGHIJKLMNOPQRSTUVWXY
25,A,ABCDEFGHIJKLMNOPQRSTUVWXYZ,ABCDEFGHIJKLMNOPQRSTUVWXYZ